name: Laravel CI

on: [push, pull_request]

jobs:
  laravel-tests:
    runs-on: ubuntu-latest

    env:
      APP_ENV: testing
      APP_KEY: base64:mJ5azSoCD/h245eh6CUAtwSR34CnOU4phvJGfUFyN4M=
      APP_DEBUG: true
      APP_URL: http://localhost

      DB_CONNECTION: sqlite
      DB_DATABASE: ":memory:"

      CACHE_DRIVER: file
      SESSION_DRIVER: array
      QUEUE_CONNECTION: sync

      MAIL_MAILER: log
      MAIL_FROM_ADDRESS: hello@example.com
      MAIL_FROM_NAME: Laravel

      JWT_SECRET: dummyjwtfordevelopment

      ULTRAMSG_INSTANCE_ID: dummy
      ULTRAMSG_TOKEN: dummy
      OPENAI_API_KEY: dummy

      NUNO_MOOD_CACHE_TTL: 1
      NUNO_GPT_RESPONSE_TTL: 30
      NUNO_MOOD_THRESHOLD: 80

    steps:
      - name: 📥 Checkout code
        uses: actions/checkout@v3

      - name: 🧱 Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.2'
          extensions: mbstring, bcmath, pdo_sqlite
          coverage: none

      - name: 📦 Install dependencies
        run: composer install --no-progress --prefer-dist --optimize-autoloader

      - name: ⚙️ Setup testing environment
        run: cp .env.testing .env


      - name: 🔐 Generate key
        run: php artisan key:generate

      - name: 🛠 Migrate database
        run: php artisan migrate --force

      - name: ✅ Run tests
        run: php artisan test
